### ISSUE TITLE
NGA Audio Alignment with ATSC

### ISSUE THREAD

**Issue by pmaness** [Dash-Industry-Forum/Audio#1]
This comment applies to both the "NGA Audio Alignment with ATSC" and "DTS" CRs.
In preparing the respective audio text, the work was done independent of the Table 10 in IOP v5 titled "Adaptation Set Attributes and Elements and Usage in DASH-IF IOPs".

An attempt should be made to reduce redundancy (and confusion) in the parameter descriptions of the respective codecs with this table. General information common to all codecs probably belongs in the table, with additional detail on the parameters (as needed) in the respective codec sections (and referenced in the table). 

For example, the description for AudioChannelConfiguration can be written as: "specifies information about the Audio channel configuration. The usage of this parameter is codec dependent. See also clauses _a.b, a.c, a.d_". This is similar to what was done in the "@codecs" parameter.

**Comment by haudiobe** [comment]
2020-06-15 IOP Call: IOP forwards this to Audio TF.

**Comment by pmaness** [comment]
Audio amendment was published and is in the document repository
