### ISSUE TITLE
Need restrict the @preselection  in MPD , when necessary info are in  AC4 codec bitstream 

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Audio#3]
Dear audio parts owners:

Related chapter  : 5.3.5 AC-4 MPD Element and Attribute Settings 

As preselection  in 23009-1 v4 , 5.3.11 shows : 

Preselections may be uniquely identified by a Preselection Tag. Users/Codecs using this Tag functionality are encouraged to provide more information on how tags defined in the MPD map to functionality in the specific codec.

If the Adaptation Set contains multiple media components multiplexed on the file-container level, then each media component is mapped to a Content Component as defined in 5.3.4.

If the Adaptation Set contains multiple media components multiplexed at the elementary-stream level, then a pre-defined experience is referenced by the Preselection.

------
So , cause it will have cases that there are many preselection tag for within one adaptations of one period ,  and the info is at codec bitstream level . It will be costly when there is no info in MPD . 

When there is no @preselection in MPD , then need parser all adaptationsets bitstream to get all necessary info when player is starting . Especially for  AC4 sub-streams , as the AC4 spec writes , only in ac4_presentation_v1_dsi of each audio frame bitstream have this info , event there is no describetion in ac4 header (maybe can be add in reversed bits)

------
My point is :  the spec should have a strict rule that when there are codec bitstream level infos , it must list in MPD level .
like : 
If the Adaptation Set contains multiple media components multiplexed at the elementary-stream level, then a pre-defined experience is referenced by the Preselection. ... 
The MPD of such contents  ,all codec level media components must described and listed  in @preselection  tags .

B.R
Huang Siyuan 
saber.huang@samsung.com

**Comment by stschr** [comment]
Dear Huang Siyuan,
from the nature of your request is suppose your concern originates from broadcast applications. And indeed, in this area signaling of all available experiences is highly desirable.
However, the general IOP (in this case the V5) is targeting much broader use cases, where the preselection element is not always supported: The preselection element was introduced in the MPEG-DASH specification with its 3rd edition in 2019. Although not precisely documented, most of the commonly used DASH profiles were defined earlier and thus, it can't be expected that preselections are supported by clients. This is the main reason why we were not able to specify a strict rule on the usage of preselections. Still, we may consider your input when any work on the “IOP for ATSC3.0” starts again.

Back to broadcasting: A DASH client is not expected to parse other data structures than the MPD. This applies to both presenting all available audio experiences to the user via the UI, and also for any "manual selection" of an audio experience where the selection choice is signaled to the decoder via the @preselection_tag.
For cases where the content provider does not signal this information in the MPD, the decoder is still capable to perform an appropriate selection: decoders provided with a set of user preferences (mainly language and accessibility needs), but also with technical requirements (e.g. rendering capabilities) will automatically select the best-suitable from all available experience.

Stephan

**Comment by AUGxhub** [comment]
MPEG-H have such cases as well
